# Generated by Django 2.0.5 on 2018-06-01 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generales', '0005_analista'),
        ('recepcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lectura_1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lectura_2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lectura_3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lectura_4', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperatura_1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperatura_2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperatura_3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperatura_4', models.DecimalField(decimal_places=2, max_digits=5)),
                ('arenas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('arcillas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('limos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('textura', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_analisis', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('analista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generales.Analista')),
                ('folio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recepcion.Recepcion')),
            ],
        ),
    ]
