# Generated by Django 2.0.5 on 2018-06-05 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0002_auto_20180604_1524'),
        ('analisis_basico', '0002_auto_20180604_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.Recepcion')),
            ],
        ),
    ]
