# Generated by Django 2.0.5 on 2018-06-22 22:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0008_auto_20180622_1254'),
        ('analisis_basico', '0004_ph_conductividadelectrica'),
    ]

    operations = [
        migrations.AddField(
            model_name='ph_conductividadelectrica',
            name='analista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generales.Analista'),
        ),
        migrations.AddField(
            model_name='ph_conductividadelectrica',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ph_conductividadelectrica',
            name='fecha_analisis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ph_conductividadelectrica',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición'),
        ),
    ]
