# Generated by Django 2.0.5 on 2018-06-24 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0002_auto_20180604_1524'),
        ('generales', '0008_auto_20180622_1254'),
        ('analisis_basico', '0005_auto_20180622_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaOrganica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase_suelo', models.CharField(max_length=100)),
                ('b1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('b2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('b3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('t', models.DecimalField(decimal_places=2, max_digits=5)),
                ('g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('N', models.DecimalField(decimal_places=2, max_digits=5)),
                ('materia_organica', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('interpretacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_analisis', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('analista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generales.Analista')),
                ('folio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recepcion.Recepcion')),
            ],
        ),
    ]
