# Generated by Django 2.0.5 on 2018-07-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_basico', '0008_puntosaturacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntosaturacion',
            name='peso_inicial_aire',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
        migrations.AlterField(
            model_name='puntosaturacion',
            name='peso_inicial_estufa',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
    ]
