# Generated by Django 2.0.5 on 2018-06-01 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('localidad', models.CharField(blank=True, max_length=200, null=True)),
                ('calle', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_exterior', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_interior', models.CharField(blank=True, max_length=20, null=True)),
                ('colonia', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo_postal', models.PositiveIntegerField()),
                ('rfc', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_1', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_2', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_3', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_electronico_1', models.EmailField(blank=True, max_length=254, null=True)),
                ('correo_electronico_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('contacto_1', models.CharField(blank=True, max_length=20, null=True)),
                ('puesto_contacto_1', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_contacto1', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_electronico_contacto_1', models.EmailField(blank=True, max_length=254, null=True)),
                ('contacto_2', models.CharField(blank=True, max_length=20, null=True)),
                ('puesto_contacto_2', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_contacto_2', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_electronico_contacto_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='generales.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='RegimenHidrico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='municipio',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='generales.Estado'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='generales.Municipio'),
        ),
    ]
