# Generated by Django 2.0.5 on 2018-06-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0004_auto_20180601_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
