# Generated by Django 2.0.5 on 2018-06-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0005_analista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
