# Generated by Django 2.0.5 on 2018-06-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0006_auto_20180604_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='contacto_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='contacto_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='puesto_contacto_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='puesto_contacto_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
