# Generated by Django 2.0.5 on 2018-06-22 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0007_auto_20180620_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cultivo',
            options={'ordering': ['nombre']},
        ),
    ]
