# Generated by Django 2.0.5 on 2018-08-08 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recepcion', '0002_auto_20180604_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadosTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textura_arenas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('textura_arcillas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('textura_limos', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('textura_textura', models.CharField(blank=True, max_length=100, null=True)),
                ('ph', models.DecimalField(decimal_places=2, max_digits=4)),
                ('clasificacion_ph', models.CharField(blank=True, max_length=100, null=True)),
                ('ce', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('clasificacion_ce', models.CharField(blank=True, max_length=100, null=True)),
                ('materia_organica', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('interpretacionMO', models.CharField(blank=True, max_length=100, null=True)),
                ('clave_color', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('densidad_aparente', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('punto_saturacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('capacidad_campo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('punto_marchitez', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nitrogeno', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('CaCo3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Carbonatos Totales')),
                ('Fe', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('Cu', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('Mn', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('Zn', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('Ca', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('Mg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('Na', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('K', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('tipo_fosforo', models.CharField(blank=True, max_length=100, null=True)),
                ('fosforo', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('ph_pasta', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ce_pasta', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('unidad_cePasta', models.CharField(blank=True, max_length=50, null=True)),
                ('CaCation', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Ca++ (meq/L)')),
                ('MgCation', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Mg++ (meq/L)')),
                ('NaCation', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Na+ (meq/L)')),
                ('KCation', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='K+ (meq/L)')),
                ('carbonatos', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Carbonatos (meq/L)')),
                ('bicarbonatos', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Bicarbonatos (meq/L)')),
                ('cloruros', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Cloruros (meq/L)')),
                ('sulfatos', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Sulfatos (meq/L)')),
                ('CaMeq', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Ca+ (meq/100g)')),
                ('MgMeq', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Mg++ (meq/100g)')),
                ('NaMeq', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Na+ (meq/100g)')),
                ('KMeq', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='K+ (meq/100g)')),
                ('Cic', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Capacidad de Intercambio Cationico (CIC)')),
                ('CaPorcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Ca+ (%)')),
                ('MgPorcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Mg+ (%)')),
                ('NaPorcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Na+ (%)')),
                ('KPorcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='K+ (%)')),
                ('Ca_Mg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Ca/Mg')),
                ('Mg_K', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Mg/K')),
                ('CaMg_K', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='(Ca+Mg)/K')),
                ('Ca_K', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Ca/K')),
                ('Ras', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='RAS')),
                ('Psi', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='PSI')),
                ('folio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recepcion.Recepcion')),
            ],
        ),
    ]
