# Generated by Django 2.0 on 2018-08-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_auto_20180808_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadostotal',
            name='cadena',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
