# Generated by Django 2.0.5 on 2018-08-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_resultadostotal_cadena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadostotal',
            name='cadena',
        ),
        migrations.AddField(
            model_name='resultadostotal',
            name='slug',
            field=models.SlugField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
