# Generated by Django 2.0 on 2018-08-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_auto_20180813_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadostotal',
            name='folio_str',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resultadostotal',
            name='organizacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resultadostotal',
            name='productor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
