# Generated by Django 2.0 on 2018-08-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_auto_20180816_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadostotal',
            name='cultivo_a_establecer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resultadostotal',
            name='cultivo_anterior',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resultadostotal',
            name='estado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resultadostotal',
            name='fecha_muestreo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultadostotal',
            name='fecha_recepcion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultadostotal',
            name='localidad_ejido',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resultadostotal',
            name='municipio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resultadostotal',
            name='nombre_predio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resultadostotal',
            name='numero_hectareas',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='resultadostotal',
            name='profundida_cm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultadostotal',
            name='regimen_hidrico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resultadostotal',
            name='rendimiento_esperado',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='resultadostotal',
            name='tipo_analisis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
