# Generated by Django 2.0.5 on 2018-07-01 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recepcion', '0002_auto_20180604_1524'),
        ('generales', '0008_auto_20180622_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nitrogeno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ml de Titulación')),
                ('B', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ml de Blanco')),
                ('N', models.DecimalField(decimal_places=3, default=0.005, max_digits=5, verbose_name='Normalidad del acido')),
                ('Vi', models.DecimalField(decimal_places=2, default=50, max_digits=5, verbose_name='Volumen Extractante')),
                ('a', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Alicuota Destilada')),
                ('p', models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='Peso de Muestra')),
                ('nitrogeno', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_analisis', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('analista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generales.Analista')),
                ('folio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recepcion.Recepcion')),
            ],
        ),
    ]
