# Generated by Django 2.0.5 on 2018-07-03 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0002_auto_20180604_1524'),
        ('generales', '0008_auto_20180622_1254'),
        ('analisis_nutrientes', '0002_carbonatostotales'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasesIntercambiables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ca', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Mg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Na', models.DecimalField(decimal_places=2, max_digits=5)),
                ('K', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_analisis', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('analista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generales.Analista')),
                ('folio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recepcion.Recepcion')),
            ],
        ),
        migrations.CreateModel(
            name='Micronutrientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fe', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Cu', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Mn', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Zn', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_analisis', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('analista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generales.Analista')),
                ('folio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recepcion.Recepcion')),
            ],
        ),
    ]
