# Generated by Django 2.0.5 on 2018-07-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_nutrientes', '0003_basesintercambiables_micronutrientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesintercambiables',
            name='Ca',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='basesintercambiables',
            name='K',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='basesintercambiables',
            name='Mg',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='basesintercambiables',
            name='Na',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='carbonatostotales',
            name='a',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='ml Titulación Blanco'),
        ),
        migrations.AlterField(
            model_name='carbonatostotales',
            name='b',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='ml Titulación Muestra'),
        ),
        migrations.AlterField(
            model_name='carbonatostotales',
            name='m',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=7, verbose_name='Molaridad de la solución'),
        ),
        migrations.AlterField(
            model_name='carbonatostotales',
            name='s',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Peso de la Muestra'),
        ),
        migrations.AlterField(
            model_name='micronutrientes',
            name='Cu',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='micronutrientes',
            name='Fe',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='micronutrientes',
            name='Mn',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='micronutrientes',
            name='Zn',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='nitrogeno',
            name='nitrogeno',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
