# Generated by Django 2.0.5 on 2018-06-04 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcion',
            name='cultivo_a_establecer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cultivo_nuevo', to='generales.Cultivo'),
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='cultivo_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cultivo_anterior', to='generales.Cultivo'),
        ),
    ]
