# Generated by Django 2.0.5 on 2018-08-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_formula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basescambio',
            name='Cic',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Capacidad de Intercambio Cationico (CIC)'),
        ),
    ]
